services:
  - type: web
    name: hdhtoys-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
